// Generated by train_large/bundle_lex_large.py from wgsl_large.py -- do not edit.
export const SHADER = `// Generated by wgsl.py -- do not edit.
// Multi-entry-point pipeline; see the module docstring for the split.

const DIM: u32 = 96u;
const EDIM: u32 = 64u;
const HEAD_HIDDEN: u32 = 192u;
const NCLASS: u32 = 9u;
const KSIZE: u32 = 5u;
const TILE: u32 = 16u;
const TILE_POOL: u32 = 4u;
const MAX_JOBS: u32 = 64u;
const NREG: u32 = 8u;
const EMB_P: u32 = 0u;
const EMB_W: u32 = 3392u;
const EMB_B: u32 = 3u;
const EMB_S: u32 = 0u;
const UP_P: u32 = 10176u;
const UP_W: u32 = 192u;
const UP_B: u32 = 1u;
const UP_S: u32 = 17u;
const UP_BI: u32 = 113u;
const FD_P: u32 = 10368u;
const FD_W: u32 = 384u;
const FD_B: u32 = 1u;
const FD_S: u32 = 209u;
const FD_BI: u32 = 273u;
const FU_P: u32 = 10752u;
const FU_W: u32 = 1536u;
const FU_B: u32 = 1u;
const FU_S: u32 = 337u;
const FU_BI: u32 = 1105u;
const GS_P: u32 = 18096u;
const GS_W: u32 = 1152u;
const GS_B: u32 = 1u;
const GS_S: u32 = 6609u;
const GS_BI: u32 = 6705u;
const GG_P: u32 = 19248u;
const GG_W: u32 = 288u;
const GG_B: u32 = 1u;
const GG_S: u32 = 6801u;
const GG_BI: u32 = 6897u;
const HH_P: u32 = 19536u;
const HH_W: u32 = 1152u;
const HH_B: u32 = 1u;
const HH_S: u32 = 6993u;
const HH_BI: u32 = 7185u;
const HO_P: u32 = 20688u;
const HO_W: u32 = 54u;
const HO_B: u32 = 1u;
const HO_S: u32 = 7377u;
const HO_BI: u32 = 7386u;
const HNORM_F: u32 = 9604u;
const FS_F: u32 = 7396u;
const FN_F: u32 = 7780u;
const NLAYER: u32 = 4u;
const FILM_RANK: u32 = 64u;
const DG_F: u32 = 9508u;
const HW_F: u32 = 7395u;
const FIELD_ROW: array<u32, 16> = array<u32, 16>(0u, 4u, 12u, 140u, 268u, 1292u, 1548u, 1564u, 1580u, 1612u, 1644u, 1652u, 1660u, 1668u, 1676u, 1684u);
const FLAG_ROW: u32 = 1688u;
const NFIELD: u32 = 16u;
const NFLAG: u32 = 8u;

// One job per workgroup_id.y. Batched calls dispatch every job together so they
// run concurrently and share one readback.
struct Job {
    token_count: u32,
    token_offset: u32,   // slice of the shared token/output buffers
    stage: u32,          // reserved for the stage-diff test harness
    stride: u32,         // per-job hidden-state stride, = maxTokens * DIM
};

@group(0) @binding(0) var<storage, read>       tokens : array<u32>;
@group(0) @binding(1) var<storage, read>       planes : array<u32>;
@group(0) @binding(2) var<storage, read>       fp     : array<f32>;
@group(0) @binding(3) var<storage, read_write> hid    : array<f32>;
@group(0) @binding(4) var<storage, read_write> scratch: array<f32>;
@group(0) @binding(5) var<storage, read_write> out_cls: array<u32>;
// A uniform array, not storage: Tint treats uniform loads indexed by a builtin
// as uniform, which is what allows \`workgroupBarrier\` inside job-dependent
// loops. A storage load here makes every barrier in the kernel illegal.
@group(0) @binding(6) var<uniform>             jobs   : array<Job, MAX_JOBS>;

var<workgroup> tA  : array<f32, 3072>;   // TILE x max(DIM, HEAD_HIDDEN) = 16 x 192
var<workgroup> tB  : array<f32, 3072>;   // TILE x 2*DIM = 16 x 192
var<workgroup> tP  : array<f32, 1536>;   // TILE_POOL x 4*DIM = 4 x 384
// Sized to DIM (96), not the 64-wide model's fixed 64: FILM_RANK (64) fits
// inside it, and film()'s "threads past FILM_RANK write 0" branch runs for
// every one of the 96 workgroup lanes.
var<workgroup> red : array<f32, 96>;
var<workgroup> lg  : array<f32, 144>;    // TILE x NCLASS

// WGSL's tanh is computed as (e^2x - 1)/(e^2x + 1) on some backends, so a
// moderately large argument overflows to inf/inf = NaN instead of saturating.
// The GELU in the head reaches that range routinely -- its cubic term hits ~90 at
// an input of ~14 -- which silently turned whole tokens into NaN logits and made
// argmax fall back to class 0. Clamping is exact: tanh(15) and sigmoid(30) are
// already 1.0 in f32.
fn tanh_s(x: f32) -> f32 { return tanh(clamp(x, -15.0, 15.0)); }
fn sigmoid_s(x: f32) -> f32 { return 1.0 / (1.0 + exp(-clamp(x, -30.0, 30.0))); }
// Matches torch.nn.functional.softplus's numerically-stable form: linear past
// the point where exp(x) would overflow or the log1p term becomes a no-op.
fn softplus_s(x: f32) -> f32 { return select(log(1.0 + exp(x)), x, x > 20.0); }

// k-bit weight from bit-planes. Used only where the row index depends on data:
// the embedding table and the depthwise kernel.
fn wgt(base: u32, wpp: u32, bits: u32, idx: u32, scale: f32) -> f32 {
    var c: u32 = 0u;
    let w = idx >> 5u;
    let b = idx & 31u;
    for (var p: u32 = 0u; p < bits; p = p + 1u) {
        c = c | (((planes[base + p * wpp + w] >> b) & 1u) << p);
    }
    if (bits == 1u) { return select(-scale, scale, c == 1u); }
    return (f32(c) - f32(1u << (bits - 1u))) * scale;
}

// Every projection is 1-bit and its rows are a multiple of 32 wide, so a whole
// row is 1-8 u32 held in registers for the life of the dispatch. Each MAC is
// then a register shift and a sign select rather than a dependent global load.
fn m1(w: u32, k: u32, x: f32) -> f32 { return select(-x, x, ((w >> k) & 1u) == 1u); }

fn dotA32(w: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w, k, tA[base + k]); }
    return a;
}
fn dotA64(w0: u32, w1: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, tA[base + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, tA[base + 32u + k]); }
    return a;
}
fn dotA96(w0: u32, w1: u32, w2: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, tA[base + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, tA[base + 32u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w2, k, tA[base + 64u + k]); }
    return a;
}
fn dotA128(w0: u32, w1: u32, w2: u32, w3: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, tA[base + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, tA[base + 32u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w2, k, tA[base + 64u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w3, k, tA[base + 96u + k]); }
    return a;
}
// 6-word/192-wide variant added for lex-large: film.down's input (2*DIM=192)
// and head_out's input (HEAD_HIDDEN=192) are both this width.
fn dotA192(w0: u32, w1: u32, w2: u32, w3: u32, w4: u32, w5: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, tA[base + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, tA[base + 32u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w2, k, tA[base + 64u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w3, k, tA[base + 96u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w4, k, tA[base + 128u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w5, k, tA[base + 160u + k]); }
    return a;
}
fn dotRed64(w0: u32, w1: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, red[k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, red[32u + k]); }
    return a;
}
fn dotRed32(w: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w, k, red[k]); }
    return a;
}
fn dotB128(w0: u32, w1: u32, w2: u32, w3: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, tB[base + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, tB[base + 32u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w2, k, tB[base + 64u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w3, k, tB[base + 96u + k]); }
    return a;
}
fn dotB32(w: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w, k, tB[base + k]); }
    return a;
}
// 6-word/192-wide variant added for lex-large: proj_out's input (2*DIM=192)
// and head_hidden's input (2*DIM=192) are both this width.
fn dotB192(w0: u32, w1: u32, w2: u32, w3: u32, w4: u32, w5: u32, base: u32) -> f32 {
    var a: f32 = 0.0;
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w0, k, tB[base + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w1, k, tB[base + 32u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w2, k, tB[base + 64u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w3, k, tB[base + 96u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w4, k, tB[base + 128u + k]); }
    for (var k: u32 = 0u; k < 32u; k = k + 1u) { a = a + m1(w5, k, tB[base + 160u + k]); }
    return a;
}

// Three words per token, not lex's two: lex-large's tokenizer (see
// lex-large/src/tokenizer.js) adds six structural fields with nowhere left to
// pack in lex's tw0/tw1 layout (tw0 is bit-for-bit full; tw1 has 2 spare bits
// out of 32), plus wider hash1/hash2 that no longer fit tw1's old field
// widths either -- so tw1 itself is repacked, not just extended.
fn tw0(o: u32, i: u32) -> u32 { return tokens[(o + i) * 3u]; }
fn tw1(o: u32, i: u32) -> u32 { return tokens[(o + i) * 3u + 1u]; }
fn tw2(o: u32, i: u32) -> u32 { return tokens[(o + i) * 3u + 2u]; }
fn tok_kind(o: u32, i: u32)  -> u32 { return  tw0(o, i)        & 3u; }
fn tok_flags(o: u32, i: u32) -> u32 { return (tw0(o, i) >> 19u) & 255u; }

fn field_id(o: u32, i: u32, f: u32) -> u32 {
    switch f {
        case 0u:  { return  tw0(o, i)        & 3u; }          // kind
        case 1u:  { return (tw0(o, i) >>  2u) & 7u; }          // len_bucket
        case 2u:  { return (tw0(o, i) >>  5u) & 127u; }        // first_char
        case 3u:  { return (tw0(o, i) >> 12u) & 127u; }        // last_char
        case 4u:  { return  tw1(o, i)        & 1023u; }        // hash1 (10 bits)
        case 5u:  { return (tw1(o, i) >> 10u) & 255u; }        // hash2 (8 bits, wider than lex's 7)
        case 6u:  { return (tw1(o, i) >> 18u) & 15u; }         // trans_prev
        case 7u:  { return (tw1(o, i) >> 22u) & 15u; }         // trans_next
        case 8u:  { return (tw1(o, i) >> 26u) & 31u; }         // sym_prev
        case 9u:  { return (tw0(o, i) >> 27u) & 31u; }         // sym_next
        case 10u: { return  tw2(o, i)        & 7u; }           // paren_depth
        case 11u: { return (tw2(o, i) >>  3u) & 7u; }          // brace_depth
        case 12u: { return (tw2(o, i) >>  6u) & 7u; }          // bracket_depth
        case 13u: { return (tw2(o, i) >>  9u) & 7u; }          // line_pos
        case 14u: { return (tw2(o, i) >> 12u) & 7u; }          // indent_bucket
        default:  { return (tw2(o, i) >> 15u) & 3u; }          // quote_state (f == 15)
    }
}

// Per-token inverse RMS for a tile, computed by the first TILE threads.
fn tile_rms(d: u32, n: u32) {
    if (d < n) {
        var s: f32 = 0.0;
        for (var k: u32 = 0u; k < DIM; k = k + 1u) {
            let v = tA[d * DIM + k];
            s = s + v * v;
        }
        red[d] = inverseSqrt(s / f32(DIM) + 1e-6);
    }
}


@compute @workgroup_size(96)
fn embed(@builtin(local_invocation_id) lid: vec3<u32>,
         @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let off = job.token_offset;
    let hbase = job.stride * wid.y;
    let r_xorig = NREG * job.stride * wid.y + 7u * job.stride;
    let base_t = wid.x * TILE;

    let up_w0 = planes[UP_P + d * 2u];
    let up_w1 = planes[UP_P + d * 2u + 1u];
    let up_s = fp[UP_S + d];
    let up_b = fp[UP_BI + d];

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (d < EDIM) {
            var acc: f32 = 0.0;
            if (t < T) {
                let kind = tok_kind(off, t);
                for (var f: u32 = 0u; f < NFIELD; f = f + 1u) {
                    // Word hashes are undefined on non-word tokens; feeding
                    // bucket 0 into every symbol would alias them together.
                    if ((f == 4u || f == 5u) && kind != 0u) { continue; }
                    let row = FIELD_ROW[f] + field_id(off, t, f);
                    acc = acc + wgt(EMB_P, EMB_W, EMB_B, row * EDIM + d, fp[EMB_S + f]);
                }
                let flags = tok_flags(off, t);
                for (var b: u32 = 0u; b < NFLAG; b = b + 1u) {
                    if (((flags >> b) & 1u) == 1u) {
                        acc = acc + wgt(EMB_P, EMB_W, EMB_B,
                                        (FLAG_ROW + b) * EDIM + d, fp[EMB_S + NFIELD]);
                    }
                }
            }
            tA[j * EDIM + d] = acc;
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let v = up_b + up_s * dotA64(up_w0, up_w1, j * EDIM);
            hid[hbase + t * DIM + d] = v;
            scratch[r_xorig + t * DIM + d] = v;
        }
    }
}


// ---- document signature and FiLM --------------------------------------------
// A linear probe recovers the language from this pooled signature at 84%
// accuracy, and the model was previously only able to use that at the very last
// layer. These two passes compute it once and turn it into a per-layer, per-
// channel scale and shift, so it reaches the depthwise conv and the recurrence.
@compute @workgroup_size(96)
fn sig_pool(@builtin(local_invocation_id) lid: vec3<u32>,
            @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let r_film = NREG * job.stride * wid.y + 6u * job.stride;

    var s: f32 = 0.0;
    var mx: f32 = -3.4e38;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let v = hid[hbase + t * DIM + d];
        s = s + v;
        mx = max(mx, v);
    }
    scratch[r_film + d] = s / max(1.0, f32(T));
    scratch[r_film + DIM + d] = mx;
}

@compute @workgroup_size(96)
fn film(@builtin(local_invocation_id) lid: vec3<u32>,
        @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let r_film = NREG * job.stride * wid.y + 6u * job.stride;

    // Signature into workgroup memory, RMS-normalized. Without the norm the
    // projection below saturates tanh for most units and stops distinguishing
    // documents at all.
    tA[d] = scratch[r_film + d];
    tA[DIM + d] = scratch[r_film + DIM + d];
    workgroupBarrier();
    var ss: f32 = 0.0;
    for (var k: u32 = 0u; k < 2u * DIM; k = k + 1u) { ss = ss + tA[k] * tA[k]; }
    let inv = inverseSqrt(ss / f32(2u * DIM) + 1e-6);
    let n0 = tA[d] * inv * fp[FN_F + d];
    let n1 = tA[DIM + d] * inv * fp[FN_F + DIM + d];
    workgroupBarrier();
    tA[d] = n0;
    tA[DIM + d] = n1;
    workgroupBarrier();
    if (d < FILM_RANK) {
        red[d] = tanh_s(fp[FD_BI + d] + fp[FD_S + d] * dotA192(
            planes[FD_P + d * 6u], planes[FD_P + d * 6u + 1u],
            planes[FD_P + d * 6u + 2u], planes[FD_P + d * 6u + 3u],
            planes[FD_P + d * 6u + 4u], planes[FD_P + d * 6u + 5u], 0u));
    } else {
        red[d] = 0.0;
    }
    workgroupBarrier();

    // 2 * DIM outputs per layer, spread across the 96 threads.
    let n_out = NLAYER * 2u * DIM;
    for (var o = d; o < n_out; o = o + 96u) {
        let raw = fp[FU_BI + o] + fp[FU_S + o] * dotRed64(planes[FU_P + o * 2u], planes[FU_P + o * 2u + 1u]);
        let l = o / (2u * DIM);
        let rem = o % (2u * DIM);
        let c = rem % DIM;
        let str = fp[FS_F + l * DIM + c];
        // k == 0 is the scale (identity at strength 0), k == 1 the shift.
        let v = select(str * tanh_s(raw), 1.0 + str * tanh_s(raw), rem < DIM);
        scratch[r_film + 2u * DIM + o] = v;
    }
}


// ---- layer 0 -------------------------------------------------------------

@compute @workgroup_size(96)
fn l0_pre(@builtin(local_invocation_id) lid: vec3<u32>,
            @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_film = sbase + 6u * job.stride;
    let base_t = wid.x * TILE;

    let gain = fp[8260u + d];
    // FiLM for this layer: scale and shift produced from the document signature.
    let gamma = scratch[r_film + 2u * DIM + (0u * 2u + 0u) * DIM + d];
    let beta = scratch[r_film + 2u * DIM + (0u * 2u + 1u) * DIM + d];
    // Normalize this tile plus its two-token halo, so the depthwise window has
    // the values it needs without a separate pass over the whole sequence.
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        tA[j * DIM + d] = select(0.0, hid[hbase + t * DIM + d], t < T);
    }
    workgroupBarrier();
    tile_rms(d, TILE);
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            scratch[r_nrm + t * DIM + d] =
                (tA[j * DIM + d] * red[j] * gain) * gamma + beta;
        }
    }
}

@compute @workgroup_size(96)
fn l0_conv(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let pic0 = planes[12348u + d * 3u];
    let pic1 = planes[12348u + d * 3u + 1u];
    let pic2 = planes[12348u + d * 3u + 2u];
    let pig0 = planes[12348u + (DIM + d) * 3u];
    let pig1 = planes[12348u + (DIM + d) * 3u + 1u];
    let pig2 = planes[12348u + (DIM + d) * 3u + 2u];
    let sc = fp[2065u + d];
    let sg = fp[2065u + DIM + d];
    let bc = fp[2257u + d];
    let bg = fp[2257u + DIM + d];
    let dbias = fp[1969u + d];
    let dws = fp[1873u + d];
    var dwv: array<f32, 5>;
    for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
        dwv[k] = wgt(12288u, 15u, 4u, d * KSIZE + k, dws);
    }

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        var acc: f32 = 0.0;
        if (t < T) {
            acc = dbias;
            for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
                let o = i32(t) + (i32(k) - i32(KSIZE / 2u)) * 1;
                if (o >= 0 && o < i32(T)) {
                    acc = acc + dwv[k] * scratch[r_nrm + u32(o) * DIM + d];
                }
            }
        }
        tA[j * DIM + d] = acc;
    }
    workgroupBarrier();

    // Low-rank input-conditioned erase. tB is zero-padded to 32 values so the
    // packed up projection remains word-aligned for ranks below 32.
    if (d < 32u) {
        for (var j: u32 = 0u; j < TILE; j = j + 1u) {
            let t = base_t + j;
            var v: f32 = 0.0;
            if (t < T && d < 16u) {
                let raw = fp[2657u + d] + fp[2641u + d] * dotA96(
                    planes[13500u + d * 3u], planes[13500u + d * 3u + 1u],
                    planes[13500u + d * 3u + 2u],
                    j * DIM);
                v = tanh_s(raw);
            }
            tB[j * 2u * DIM + d] = v;
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let ef = fp[2865u + d] + fp[2673u + d] * dotB32(
                planes[13548u + d], j * 2u * DIM);
            let eb = fp[2865u + DIM + d] + fp[2673u + DIM + d] * dotB32(
                planes[13548u + DIM + d], j * 2u * DIM);
            scratch[r_fw + t * DIM + d] = sigmoid_s(ef);
            scratch[r_bw + t * DIM + d] = sigmoid_s(eb);
        }
    }
    workgroupBarrier();

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let cand = bc + sc * dotA96(pic0, pic1, pic2, j * DIM);
            let gate = bg + sg * dotA96(pig0, pig1, pig2, j * DIM);
            scratch[r_b + t * DIM + d] = tanh_s(cand) * sigmoid_s(gate);
        }
    }
}


@compute @workgroup_size(96)
fn l0_scan(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;

    let base_f = sigmoid_s(fp[8068u + d]);
    let base_b = sigmoid_s(fp[8164u + d]);
    var hf: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let bt = scratch[r_b + t * DIM + d];
        let aft = base_f * (1.0 - scratch[r_fw + t * DIM + d]);
        hf = aft * hf + bt;
        scratch[r_fw + t * DIM + d] = hf;
    }
    var hb: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let ti = T - 1u - t;
        let bt = scratch[r_b + ti * DIM + d];
        let abt = base_b * (1.0 - scratch[r_bw + ti * DIM + d]);
        hb = abt * hb + bt;
        scratch[r_bw + ti * DIM + d] = hb;
    }
}


@compute @workgroup_size(96)
fn l0_post(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let po0 = planes[12924u + d * 6u];
    let po1 = planes[12924u + d * 6u + 1u];
    let po2 = planes[12924u + d * 6u + 2u];
    let po3 = planes[12924u + d * 6u + 3u];
    let po4 = planes[12924u + d * 6u + 4u];
    let po5 = planes[12924u + d * 6u + 5u];
    let spo = fp[2449u + d];
    let bpo = fp[2545u + d];
    let og = sigmoid_s(fp[7972u + d]);

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            tB[j * 2u * DIM + d]       = scratch[r_fw + t * DIM + d];
            tB[j * 2u * DIM + DIM + d] = scratch[r_bw + t * DIM + d];
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let y = bpo + spo * dotB192(po0, po1, po2, po3, po4, po5, j * 2u * DIM);
            hid[hbase + t * DIM + d] = hid[hbase + t * DIM + d] + y * og;
        }
    }
}


// ---- layer 1 -------------------------------------------------------------

@compute @workgroup_size(96)
fn l1_pre(@builtin(local_invocation_id) lid: vec3<u32>,
            @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_film = sbase + 6u * job.stride;
    let base_t = wid.x * TILE;

    let gain = fp[8644u + d];
    // FiLM for this layer: scale and shift produced from the document signature.
    let gamma = scratch[r_film + 2u * DIM + (1u * 2u + 0u) * DIM + d];
    let beta = scratch[r_film + 2u * DIM + (1u * 2u + 1u) * DIM + d];
    // Normalize this tile plus its two-token halo, so the depthwise window has
    // the values it needs without a separate pass over the whole sequence.
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        tA[j * DIM + d] = select(0.0, hid[hbase + t * DIM + d], t < T);
    }
    workgroupBarrier();
    tile_rms(d, TILE);
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            scratch[r_nrm + t * DIM + d] =
                (tA[j * DIM + d] * red[j] * gain) * gamma + beta;
        }
    }
}

@compute @workgroup_size(96)
fn l1_conv(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let pic0 = planes[13800u + d * 3u];
    let pic1 = planes[13800u + d * 3u + 1u];
    let pic2 = planes[13800u + d * 3u + 2u];
    let pig0 = planes[13800u + (DIM + d) * 3u];
    let pig1 = planes[13800u + (DIM + d) * 3u + 1u];
    let pig2 = planes[13800u + (DIM + d) * 3u + 2u];
    let sc = fp[3249u + d];
    let sg = fp[3249u + DIM + d];
    let bc = fp[3441u + d];
    let bg = fp[3441u + DIM + d];
    let dbias = fp[3153u + d];
    let dws = fp[3057u + d];
    var dwv: array<f32, 5>;
    for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
        dwv[k] = wgt(13740u, 15u, 4u, d * KSIZE + k, dws);
    }

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        var acc: f32 = 0.0;
        if (t < T) {
            acc = dbias;
            for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
                let o = i32(t) + (i32(k) - i32(KSIZE / 2u)) * 2;
                if (o >= 0 && o < i32(T)) {
                    acc = acc + dwv[k] * scratch[r_nrm + u32(o) * DIM + d];
                }
            }
        }
        tA[j * DIM + d] = acc;
    }
    workgroupBarrier();

    // Low-rank input-conditioned erase. tB is zero-padded to 32 values so the
    // packed up projection remains word-aligned for ranks below 32.
    if (d < 32u) {
        for (var j: u32 = 0u; j < TILE; j = j + 1u) {
            let t = base_t + j;
            var v: f32 = 0.0;
            if (t < T && d < 16u) {
                let raw = fp[3841u + d] + fp[3825u + d] * dotA96(
                    planes[14952u + d * 3u], planes[14952u + d * 3u + 1u],
                    planes[14952u + d * 3u + 2u],
                    j * DIM);
                v = tanh_s(raw);
            }
            tB[j * 2u * DIM + d] = v;
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let ef = fp[4049u + d] + fp[3857u + d] * dotB32(
                planes[15000u + d], j * 2u * DIM);
            let eb = fp[4049u + DIM + d] + fp[3857u + DIM + d] * dotB32(
                planes[15000u + DIM + d], j * 2u * DIM);
            scratch[r_fw + t * DIM + d] = sigmoid_s(ef);
            scratch[r_bw + t * DIM + d] = sigmoid_s(eb);
        }
    }
    workgroupBarrier();

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let cand = bc + sc * dotA96(pic0, pic1, pic2, j * DIM);
            let gate = bg + sg * dotA96(pig0, pig1, pig2, j * DIM);
            scratch[r_b + t * DIM + d] = tanh_s(cand) * sigmoid_s(gate);
        }
    }
}


@compute @workgroup_size(96)
fn l1_scan(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;

    let base_f = sigmoid_s(fp[8452u + d]);
    let base_b = sigmoid_s(fp[8548u + d]);
    var hf: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let bt = scratch[r_b + t * DIM + d];
        let aft = base_f * (1.0 - scratch[r_fw + t * DIM + d]);
        hf = aft * hf + bt;
        scratch[r_fw + t * DIM + d] = hf;
    }
    var hb: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let ti = T - 1u - t;
        let bt = scratch[r_b + ti * DIM + d];
        let abt = base_b * (1.0 - scratch[r_bw + ti * DIM + d]);
        hb = abt * hb + bt;
        scratch[r_bw + ti * DIM + d] = hb;
    }
}


@compute @workgroup_size(96)
fn l1_post(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let po0 = planes[14376u + d * 6u];
    let po1 = planes[14376u + d * 6u + 1u];
    let po2 = planes[14376u + d * 6u + 2u];
    let po3 = planes[14376u + d * 6u + 3u];
    let po4 = planes[14376u + d * 6u + 4u];
    let po5 = planes[14376u + d * 6u + 5u];
    let spo = fp[3633u + d];
    let bpo = fp[3729u + d];
    let og = sigmoid_s(fp[8356u + d]);

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            tB[j * 2u * DIM + d]       = scratch[r_fw + t * DIM + d];
            tB[j * 2u * DIM + DIM + d] = scratch[r_bw + t * DIM + d];
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let y = bpo + spo * dotB192(po0, po1, po2, po3, po4, po5, j * 2u * DIM);
            hid[hbase + t * DIM + d] = hid[hbase + t * DIM + d] + y * og;
        }
    }
}


// ---- layer 2 -------------------------------------------------------------

@compute @workgroup_size(96)
fn l2_pre(@builtin(local_invocation_id) lid: vec3<u32>,
            @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_film = sbase + 6u * job.stride;
    let base_t = wid.x * TILE;

    let gain = fp[9028u + d];
    // FiLM for this layer: scale and shift produced from the document signature.
    let gamma = scratch[r_film + 2u * DIM + (2u * 2u + 0u) * DIM + d];
    let beta = scratch[r_film + 2u * DIM + (2u * 2u + 1u) * DIM + d];
    // Normalize this tile plus its two-token halo, so the depthwise window has
    // the values it needs without a separate pass over the whole sequence.
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        tA[j * DIM + d] = select(0.0, hid[hbase + t * DIM + d], t < T);
    }
    workgroupBarrier();
    tile_rms(d, TILE);
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            scratch[r_nrm + t * DIM + d] =
                (tA[j * DIM + d] * red[j] * gain) * gamma + beta;
        }
    }
}

@compute @workgroup_size(96)
fn l2_conv(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let pic0 = planes[15252u + d * 3u];
    let pic1 = planes[15252u + d * 3u + 1u];
    let pic2 = planes[15252u + d * 3u + 2u];
    let pig0 = planes[15252u + (DIM + d) * 3u];
    let pig1 = planes[15252u + (DIM + d) * 3u + 1u];
    let pig2 = planes[15252u + (DIM + d) * 3u + 2u];
    let sc = fp[4433u + d];
    let sg = fp[4433u + DIM + d];
    let bc = fp[4625u + d];
    let bg = fp[4625u + DIM + d];
    let dbias = fp[4337u + d];
    let dws = fp[4241u + d];
    var dwv: array<f32, 5>;
    for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
        dwv[k] = wgt(15192u, 15u, 4u, d * KSIZE + k, dws);
    }

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        var acc: f32 = 0.0;
        if (t < T) {
            acc = dbias;
            for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
                let o = i32(t) + (i32(k) - i32(KSIZE / 2u)) * 4;
                if (o >= 0 && o < i32(T)) {
                    acc = acc + dwv[k] * scratch[r_nrm + u32(o) * DIM + d];
                }
            }
        }
        tA[j * DIM + d] = acc;
    }
    workgroupBarrier();

    // Low-rank input-conditioned erase. tB is zero-padded to 32 values so the
    // packed up projection remains word-aligned for ranks below 32.
    if (d < 32u) {
        for (var j: u32 = 0u; j < TILE; j = j + 1u) {
            let t = base_t + j;
            var v: f32 = 0.0;
            if (t < T && d < 16u) {
                let raw = fp[5025u + d] + fp[5009u + d] * dotA96(
                    planes[16404u + d * 3u], planes[16404u + d * 3u + 1u],
                    planes[16404u + d * 3u + 2u],
                    j * DIM);
                v = tanh_s(raw);
            }
            tB[j * 2u * DIM + d] = v;
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let ef = fp[5233u + d] + fp[5041u + d] * dotB32(
                planes[16452u + d], j * 2u * DIM);
            let eb = fp[5233u + DIM + d] + fp[5041u + DIM + d] * dotB32(
                planes[16452u + DIM + d], j * 2u * DIM);
            scratch[r_fw + t * DIM + d] = sigmoid_s(ef);
            scratch[r_bw + t * DIM + d] = sigmoid_s(eb);
        }
    }
    workgroupBarrier();

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let cand = bc + sc * dotA96(pic0, pic1, pic2, j * DIM);
            let gate = bg + sg * dotA96(pig0, pig1, pig2, j * DIM);
            scratch[r_b + t * DIM + d] = tanh_s(cand) * sigmoid_s(gate);
        }
    }
}


@compute @workgroup_size(96)
fn l2_scan(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;

    let base_f = sigmoid_s(fp[8836u + d]);
    let base_b = sigmoid_s(fp[8932u + d]);
    var hf: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let bt = scratch[r_b + t * DIM + d];
        let aft = base_f * (1.0 - scratch[r_fw + t * DIM + d]);
        hf = aft * hf + bt;
        scratch[r_fw + t * DIM + d] = hf;
    }
    var hb: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let ti = T - 1u - t;
        let bt = scratch[r_b + ti * DIM + d];
        let abt = base_b * (1.0 - scratch[r_bw + ti * DIM + d]);
        hb = abt * hb + bt;
        scratch[r_bw + ti * DIM + d] = hb;
    }
}


@compute @workgroup_size(96)
fn l2_post(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let po0 = planes[15828u + d * 6u];
    let po1 = planes[15828u + d * 6u + 1u];
    let po2 = planes[15828u + d * 6u + 2u];
    let po3 = planes[15828u + d * 6u + 3u];
    let po4 = planes[15828u + d * 6u + 4u];
    let po5 = planes[15828u + d * 6u + 5u];
    let spo = fp[4817u + d];
    let bpo = fp[4913u + d];
    let og = sigmoid_s(fp[8740u + d]);

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            tB[j * 2u * DIM + d]       = scratch[r_fw + t * DIM + d];
            tB[j * 2u * DIM + DIM + d] = scratch[r_bw + t * DIM + d];
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let y = bpo + spo * dotB192(po0, po1, po2, po3, po4, po5, j * 2u * DIM);
            hid[hbase + t * DIM + d] = hid[hbase + t * DIM + d] + y * og;
        }
    }
}


// ---- layer 3 -------------------------------------------------------------

@compute @workgroup_size(96)
fn l3_pre(@builtin(local_invocation_id) lid: vec3<u32>,
            @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_film = sbase + 6u * job.stride;
    let base_t = wid.x * TILE;

    let gain = fp[9412u + d];
    // FiLM for this layer: scale and shift produced from the document signature.
    let gamma = scratch[r_film + 2u * DIM + (3u * 2u + 0u) * DIM + d];
    let beta = scratch[r_film + 2u * DIM + (3u * 2u + 1u) * DIM + d];
    // Normalize this tile plus its two-token halo, so the depthwise window has
    // the values it needs without a separate pass over the whole sequence.
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        tA[j * DIM + d] = select(0.0, hid[hbase + t * DIM + d], t < T);
    }
    workgroupBarrier();
    tile_rms(d, TILE);
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            scratch[r_nrm + t * DIM + d] =
                (tA[j * DIM + d] * red[j] * gain) * gamma + beta;
        }
    }
}

@compute @workgroup_size(96)
fn l3_conv(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_nrm = sbase;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let pic0 = planes[16704u + d * 3u];
    let pic1 = planes[16704u + d * 3u + 1u];
    let pic2 = planes[16704u + d * 3u + 2u];
    let pig0 = planes[16704u + (DIM + d) * 3u];
    let pig1 = planes[16704u + (DIM + d) * 3u + 1u];
    let pig2 = planes[16704u + (DIM + d) * 3u + 2u];
    let sc = fp[5617u + d];
    let sg = fp[5617u + DIM + d];
    let bc = fp[5809u + d];
    let bg = fp[5809u + DIM + d];
    let dbias = fp[5521u + d];
    let dws = fp[5425u + d];
    var dwv: array<f32, 5>;
    for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
        dwv[k] = wgt(16644u, 15u, 4u, d * KSIZE + k, dws);
    }

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        var acc: f32 = 0.0;
        if (t < T) {
            acc = dbias;
            for (var k: u32 = 0u; k < KSIZE; k = k + 1u) {
                let o = i32(t) + (i32(k) - i32(KSIZE / 2u)) * 8;
                if (o >= 0 && o < i32(T)) {
                    acc = acc + dwv[k] * scratch[r_nrm + u32(o) * DIM + d];
                }
            }
        }
        tA[j * DIM + d] = acc;
    }
    workgroupBarrier();

    // Low-rank input-conditioned erase. tB is zero-padded to 32 values so the
    // packed up projection remains word-aligned for ranks below 32.
    if (d < 32u) {
        for (var j: u32 = 0u; j < TILE; j = j + 1u) {
            let t = base_t + j;
            var v: f32 = 0.0;
            if (t < T && d < 16u) {
                let raw = fp[6209u + d] + fp[6193u + d] * dotA96(
                    planes[17856u + d * 3u], planes[17856u + d * 3u + 1u],
                    planes[17856u + d * 3u + 2u],
                    j * DIM);
                v = tanh_s(raw);
            }
            tB[j * 2u * DIM + d] = v;
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let ef = fp[6417u + d] + fp[6225u + d] * dotB32(
                planes[17904u + d], j * 2u * DIM);
            let eb = fp[6417u + DIM + d] + fp[6225u + DIM + d] * dotB32(
                planes[17904u + DIM + d], j * 2u * DIM);
            scratch[r_fw + t * DIM + d] = sigmoid_s(ef);
            scratch[r_bw + t * DIM + d] = sigmoid_s(eb);
        }
    }
    workgroupBarrier();

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let cand = bc + sc * dotA96(pic0, pic1, pic2, j * DIM);
            let gate = bg + sg * dotA96(pig0, pig1, pig2, j * DIM);
            scratch[r_b + t * DIM + d] = tanh_s(cand) * sigmoid_s(gate);
        }
    }
}


@compute @workgroup_size(96)
fn l3_scan(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let sbase = NREG * job.stride * wid.y;
    let r_b = sbase + job.stride;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;

    let base_f = sigmoid_s(fp[9220u + d]);
    let base_b = sigmoid_s(fp[9316u + d]);
    var hf: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let bt = scratch[r_b + t * DIM + d];
        let aft = base_f * (1.0 - scratch[r_fw + t * DIM + d]);
        hf = aft * hf + bt;
        scratch[r_fw + t * DIM + d] = hf;
    }
    var hb: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let ti = T - 1u - t;
        let bt = scratch[r_b + ti * DIM + d];
        let abt = base_b * (1.0 - scratch[r_bw + ti * DIM + d]);
        hb = abt * hb + bt;
        scratch[r_bw + ti * DIM + d] = hb;
    }
}


@compute @workgroup_size(96)
fn l3_post(@builtin(local_invocation_id) lid: vec3<u32>,
             @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_fw = sbase + 2u * job.stride;
    let r_bw = sbase + 3u * job.stride;
    let base_t = wid.x * TILE;

    let po0 = planes[17280u + d * 6u];
    let po1 = planes[17280u + d * 6u + 1u];
    let po2 = planes[17280u + d * 6u + 2u];
    let po3 = planes[17280u + d * 6u + 3u];
    let po4 = planes[17280u + d * 6u + 4u];
    let po5 = planes[17280u + d * 6u + 5u];
    let spo = fp[6001u + d];
    let bpo = fp[6097u + d];
    let og = sigmoid_s(fp[9124u + d]);

    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            tB[j * 2u * DIM + d]       = scratch[r_fw + t * DIM + d];
            tB[j * 2u * DIM + DIM + d] = scratch[r_bw + t * DIM + d];
        }
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let y = bpo + spo * dotB192(po0, po1, po2, po3, po4, po5, j * 2u * DIM);
            hid[hbase + t * DIM + d] = hid[hbase + t * DIM + d] + y * og;
        }
    }
}


// ---- file-scale context ----------------------------------------------------
@compute @workgroup_size(96)
fn pool_reduce(@builtin(local_invocation_id) lid: vec3<u32>,
               @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_pre = sbase;                       // reuses the normalized-input region
    let r_suf = sbase + job.stride;          // reuses the scan-input region
    let r_stat = sbase + 5u * job.stride;

    let dgw = fp[9508u + d];
    var s: f32 = 0.0;    // plain sum, still feeds the sequence-mean stat below
    var sg: f32 = 0.0;   // decl-gated sum, feeds the prefix mean only
    var sdg: f32 = 0.0;
    var mx: f32 = -3.4e38;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let v = hid[hbase + t * DIM + d];
        s = s + v;
        mx = max(mx, v);
        let dg = sigmoid_s(v * dgw);
        sg = sg + v * dg;
        sdg = sdg + dg;
        scratch[r_pre + t * DIM + d] = sg / max(1.0, sdg);
    }
    var sb: f32 = 0.0;
    for (var t: u32 = 0u; t < T; t = t + 1u) {
        let ti = T - 1u - t;
        sb = sb + hid[hbase + ti * DIM + d];
        scratch[r_suf + ti * DIM + d] = sb / f32(t + 1u);
    }
    scratch[r_stat + d] = s / max(1.0, f32(T));
    scratch[r_stat + DIM + d] = mx;
}


@compute @workgroup_size(96)
fn pool_apply(@builtin(local_invocation_id) lid: vec3<u32>,
              @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_pre = sbase;
    let r_suf = sbase + job.stride;
    let r_ctx = sbase + 4u * job.stride;
    let r_stat = sbase + 5u * job.stride;
    let base_t = wid.x * TILE_POOL;

    let gs0 = planes[GS_P + d * 12u];
    let gs1 = planes[GS_P + d * 12u + 1u];
    let gs2 = planes[GS_P + d * 12u + 2u];
    let gs3 = planes[GS_P + d * 12u + 3u];
    let gs4 = planes[GS_P + d * 12u + 4u];
    let gs5 = planes[GS_P + d * 12u + 5u];
    let gs6 = planes[GS_P + d * 12u + 6u];
    let gs7 = planes[GS_P + d * 12u + 7u];
    let gs8 = planes[GS_P + d * 12u + 8u];
    let gs9 = planes[GS_P + d * 12u + 9u];
    let gs10 = planes[GS_P + d * 12u + 10u];
    let gs11 = planes[GS_P + d * 12u + 11u];
    let gss = fp[GS_S + d];
    let gsb = fp[GS_BI + d];
    let gg0 = planes[GG_P + d * 3u];
    let gg1 = planes[GG_P + d * 3u + 1u];
    let gg2 = planes[GG_P + d * 3u + 2u];
    let ggs = fp[GG_S + d];
    let ggb = fp[GG_BI + d];

    for (var j: u32 = 0u; j < TILE_POOL; j = j + 1u) {
        let t = base_t + j;
        let ok = t < T;
        tP[j * 4u * DIM + d]             = scratch[r_stat + d];
        tP[j * 4u * DIM + DIM + d]       = scratch[r_stat + DIM + d];
        tP[j * 4u * DIM + 2u * DIM + d]  = select(0.0, scratch[r_pre + t * DIM + d], ok);
        tP[j * 4u * DIM + 3u * DIM + d]  = select(0.0, scratch[r_suf + t * DIM + d], ok);
        tA[j * DIM + d] = select(0.0, hid[hbase + t * DIM + d], ok);
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE_POOL; j = j + 1u) {
        let t = base_t + j;
        if (t < T) {
            let b = j * 4u * DIM;
            var acc: f32 = 0.0;
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs0, k, tP[b + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs1, k, tP[b + 32u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs2, k, tP[b + 64u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs3, k, tP[b + 96u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs4, k, tP[b + 128u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs5, k, tP[b + 160u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs6, k, tP[b + 192u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs7, k, tP[b + 224u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs8, k, tP[b + 256u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs9, k, tP[b + 288u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs10, k, tP[b + 320u + k]); }
            for (var k: u32 = 0u; k < 32u; k = k + 1u) { acc = acc + m1(gs11, k, tP[b + 352u + k]); }
            let ctx = tanh_s(gsb + gss * acc);
            let g = sigmoid_s(ggb + ggs * dotA96(gg0, gg1, gg2, j * DIM));
            scratch[r_ctx + t * DIM + d] = ctx * g;
        }
    }
}

// ---- classifier head -------------------------------------------------------
@compute @workgroup_size(96)
fn head(@builtin(local_invocation_id) lid: vec3<u32>,
        @builtin(workgroup_id) wid: vec3<u32>) {
    let d = lid.x;
    let job = jobs[wid.y];
    let T = job.token_count;
    let off = job.token_offset;
    let hbase = job.stride * wid.y;
    let sbase = NREG * job.stride * wid.y;
    let r_ctx = sbase + 4u * job.stride;
    let r_xorig = sbase + 7u * job.stride;
    let base_t = wid.x * TILE;

    let hgain = fp[HNORM_F + d];
    let o0 = d;
    let o1 = DIM + d;
    let h0a = planes[HH_P + o0 * 6u];
    let h0b = planes[HH_P + o0 * 6u + 1u];
    let h0c = planes[HH_P + o0 * 6u + 2u];
    let h0d = planes[HH_P + o0 * 6u + 3u];
    let h0e = planes[HH_P + o0 * 6u + 4u];
    let h0f = planes[HH_P + o0 * 6u + 5u];
    var h1a: u32 = 0u; var h1b: u32 = 0u; var h1c: u32 = 0u; var h1d: u32 = 0u;
    var h1e: u32 = 0u; var h1f: u32 = 0u;
    if (o1 < HEAD_HIDDEN) {
        h1a = planes[HH_P + o1 * 6u];
        h1b = planes[HH_P + o1 * 6u + 1u];
        h1c = planes[HH_P + o1 * 6u + 2u];
        h1d = planes[HH_P + o1 * 6u + 3u];
        h1e = planes[HH_P + o1 * 6u + 4u];
        h1f = planes[HH_P + o1 * 6u + 5u];
    }
    // head_out is 9 rows; thread c owns class c, so the final matmul is nine
    // parallel dots rather than one thread doing all of them.
    var ho0: u32 = 0u; var ho1: u32 = 0u; var ho2: u32 = 0u;
    var ho3: u32 = 0u; var ho4: u32 = 0u; var ho5: u32 = 0u;
    if (d < NCLASS) {
        ho0 = planes[HO_P + d * 6u];
        ho1 = planes[HO_P + d * 6u + 1u];
        ho2 = planes[HO_P + d * 6u + 2u];
        ho3 = planes[HO_P + d * 6u + 3u];
        ho4 = planes[HO_P + d * 6u + 4u];
        ho5 = planes[HO_P + d * 6u + 5u];
    }

    // The pre-layer embedding folded back in at strength fp[HW_F] -- zero
    // unless the checkpoint has a highway_scale parameter, in which case it
    // gives the classifier a direct path to the raw token identity alongside
    // whatever the recurrent layers built on top of it.
    let hw: f32 = fp[HW_F];
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        let xv = select(0.0, hid[hbase + t * DIM + d], t < T);
        let xo = select(0.0, scratch[r_xorig + t * DIM + d], t < T);
        tA[j * DIM + d] = xv + hw * xo;
    }
    workgroupBarrier();
    tile_rms(d, TILE);
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let t = base_t + j;
        tB[j * 2u * DIM + d] = tA[j * DIM + d] * red[j] * hgain;
        tB[j * 2u * DIM + DIM + d] = select(0.0, scratch[r_ctx + t * DIM + d], t < T);
    }
    workgroupBarrier();
    for (var j: u32 = 0u; j < TILE; j = j + 1u) {
        let a0 = fp[HH_BI + o0] + fp[HH_S + o0] * dotB192(h0a, h0b, h0c, h0d, h0e, h0f, j * 2u * DIM);
        let c0 = 0.7978845608 * (a0 + 0.044715 * a0 * a0 * a0);
        tA[j * HEAD_HIDDEN + o0] = 0.5 * a0 * (1.0 + tanh_s(c0));
        if (o1 < HEAD_HIDDEN) {
            let a1 = fp[HH_BI + o1] + fp[HH_S + o1] * dotB192(h1a, h1b, h1c, h1d, h1e, h1f, j * 2u * DIM);
            let c1 = 0.7978845608 * (a1 + 0.044715 * a1 * a1 * a1);
            tA[j * HEAD_HIDDEN + o1] = 0.5 * a1 * (1.0 + tanh_s(c1));
        }
    }
    workgroupBarrier();
    if (d < NCLASS) {
        for (var j: u32 = 0u; j < TILE; j = j + 1u) {
            lg[j * NCLASS + d] = fp[HO_BI + d] + fp[HO_S + d]
                * dotA192(ho0, ho1, ho2, ho3, ho4, ho5, j * HEAD_HIDDEN);
        }
    }
    workgroupBarrier();
    if (d < TILE) {
        let t = base_t + d;
        if (t < T) {
            var best: u32 = 0u;
            var bestv: f32 = lg[d * NCLASS];
            for (var c: u32 = 1u; c < NCLASS; c = c + 1u) {
                let v = lg[d * NCLASS + c];
                if (v > bestv) { bestv = v; best = c; }
            }
            out_cls[off + t] = best;
        }
    }
}
`;
