"""
BESPOKE fork of train/bundle_lex.py for the lex-large package: bakes the
lex-large checkpoint and train_large/wgsl_large.py's generated shader into
lex-large/src. See wgsl_large.py's module docstring for why this uses its own
generator instead of train/wgsl.py.

Bakes the exported model and generated shader into the `lex` package sources.

The packed bit planes are emitted as byte-aligned hex and the fp16 headers plus
8-bit scalar codes as base64, matching the compact v2 bundle format. The
format-aware runtime keeps decoding the promoted v1 artifact until a trained
v2 checkpoint is explicitly bundled.
"""

from __future__ import annotations

import argparse
import base64
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'train'))

import wgsl_large as wgsl  # bespoke generator -- see its module docstring


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--checkpoint-dir', default='./checkpoints_student')
    ap.add_argument('--lex-src', default='../lex-large/src')
    args = ap.parse_args()

    ck = Path(args.checkpoint_dir)
    out = Path(args.lex_src)
    out.mkdir(parents=True, exist_ok=True)

    meta = json.loads((ck / 'weights.meta.json').read_text())
    if meta.get('feature_version') != 2 or meta.get('scalar_bits') != 8:
        raise ValueError('the upgraded lex-large bundle requires v2 features and 8-bit scalars')
    blob = (ck / 'weights.bin').read_bytes()
    nw = meta['plane_words']
    planes_hex = blob[:nw * 4].hex()
    scalars_b64 = base64.b64encode(blob[nw * 4:]).decode()

    slim = {k: meta[k] for k in
            ('format', 'config', 'feature_version', 'plane_words', 'f16_count', 'f16_stream_count',
             'u8_count', 'scalar_segments', 'plane_bytes', 'f16_bytes',
             'scalar_bits', 'total_bytes', 'parameters')}
    steps = wgsl.pipeline_order(meta['config']['n_layers'])
    (out / 'weights.js').write_text(
        '// Generated by train_large/bundle_lex_large.py -- do not edit.\n'
        f'// {meta["parameters"]:,} parameters, {meta["total_bytes"] / 1024:.2f} KB packed.\n\n'
        f'export const META = {json.dumps(slim, indent=2)};\n\n'
        '// Entry points in execution order. `tile` is the tokens-per-workgroup for\n'
        '// the token-parallel passes; 0 means the pass needs the whole sequence in\n'
        '// one workgroup because it is sequential in t.\n'
        f'export const PIPELINE = {json.dumps(steps)};\n\n'
        f'export const WEIGHTS_PLANES_HEX =\n  "{planes_hex}";\n\n'
        f'export const WEIGHTS_SCALARS_B64 =\n  "{scalars_b64}";\n')

    shader = wgsl.generate(meta)
    (out / 'shader.wgsl').write_text(shader)
    escaped = shader.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    (out / 'shader.js').write_text(
        '// Generated by train_large/bundle_lex_large.py from wgsl_large.py -- do not edit.\n'
        f'export const SHADER = `{escaped}`;\n')

    print(f'bundled {meta["total_bytes"] / 1024:.2f} KB of weights '
          f'({len(planes_hex) / 1024:.1f} KB plane hex + '
          f'{len(scalars_b64) / 1024:.1f} KB scalar base64) '
          f'+ {len(shader) / 1024:.1f} KB shader -> {out}')


if __name__ == '__main__':
    main()
