"""
Emits the demo's train_large corpus bench: every language with usable raw
files under train_large/corpus/raw, scored against Shiki like the other two
demo corpora (see train/make_demo_corpus.py, which this mirrors) but drawn
from the 185-grammar target set instead of the 52-language primary one.

Every file here is out-of-distribution for lex-lite (trained on the 52-
language set) and in-distribution house style for lex-large -- this corpus
exists to show breadth of coverage, not a train/test split, so it takes
every file rather than filtering to a held-out split.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from languages import TARGET_LANGUAGES, shiki_id, weights

MAX_CHARS = 6_000
MIN_CHARS = 300


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--raw', default='./corpus/raw')
    ap.add_argument('--out', default='../demo/src/corpus_large.js')
    ap.add_argument('--per-lang', type=int, default=10)
    args = ap.parse_args()

    import random
    rng = random.Random(20260912)
    files = []
    langs_seen = set()
    for lang in TARGET_LANGUAGES:
        d = Path(args.raw) / lang
        if not d.is_dir():
            continue
        pool = [p for p in sorted(d.iterdir()) if p.is_file()]
        rng.shuffle(pool)
        picked = 0
        used: set[str] = set()
        for require_band in (True, False):
            for p in pool:
                if picked >= args.per_lang:
                    break
                if p.name in used:
                    continue
                try:
                    text = p.read_text(encoding='utf-8', errors='ignore')
                except OSError:
                    continue
                if len(text) < MIN_CHARS:
                    continue
                if len(text) > MAX_CHARS:
                    if require_band:
                        continue
                    cut = text.rfind('\n', 0, MAX_CHARS)
                    text = text[:cut if cut > MIN_CHARS else MAX_CHARS]
                files.append({'lang': lang, 'shikiLang': shiki_id(lang),
                              'name': p.name[:60], 'code': text})
                used.add(p.name)
                picked += 1
            if picked >= args.per_lang:
                break
        if picked:
            langs_seen.add(lang)

    w = weights()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    header = ('// Generated by train_large/make_demo_corpus_large.py -- do not edit.\n'
               '// Every usable file from train_large/corpus/raw across the\n'
               '// 185-grammar target set (not a train/test split).\n\n')
    body = (f'export const WEIGHTS_LARGE = {json.dumps(w, indent=2)};\n\n'
            f'export const CORPUS_LARGE = {json.dumps(files)};\n')
    out.write_text(header + body)
    print(f'{len(files)} files across {len(langs_seen)}/{len(TARGET_LANGUAGES)} languages '
          f'-> {out}  ({out.stat().st_size / 1024:.0f} KB)')


if __name__ == '__main__':
    main()
