"""
Emits the demo's train_large corpus bench: held-out test-split files from
train_large/corpus/raw across the 185-grammar target set, scored like the
other two demo corpora (see train/make_demo_corpus.py, which this mirrors).

Files are drawn only from the frozen test split -- the same content-hash
`split_of` rule build_dataset.py uses -- and only from files that actually
received teacher labels, so no bench file was seen in training and the score
is comparable to the training log's held-out WEIGHTED metric.

Each file records its labelling teacher. Shiki-taught grammars are scored
against Shiki; the Highlight.js-taught grammars Shiki does not bundle are
scored against Highlight.js with the same nine-class mapping the labelling
pipeline used (label_encode_thread.mjs), rather than silently dropped.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
from pathlib import Path

from languages import TARGET_LANGUAGES, shiki_id, teacher, weights

MAX_CHARS = 6_000
MIN_CHARS = 300


def split_of(text: str, val_pct: int = 5, test_pct: int = 5) -> str:
    """Mirror of train/data_pipeline.py's split_of (kept local so this script
    does not need torch)."""
    h = int(hashlib.sha1(text.encode('utf-8', errors='ignore')).hexdigest()[:8], 16) % 100
    if h < test_pct:
        return 'test'
    if h < test_pct + val_pct:
        return 'val'
    return 'train'


def labelled_paths(label_dir: Path) -> set[str]:
    paths = set()
    for shard in sorted(label_dir.glob('labels.*.tsv')):
        with shard.open() as fh:
            for line in fh:
                path, _, rle = line.rstrip('\n').partition('\t')
                if rle:
                    paths.add(str(Path(path).resolve()))
    return paths


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--raw', default='./corpus/raw')
    ap.add_argument('--labels', default='./corpus/labels')
    ap.add_argument('--out', default='../demo/src/corpus_large.js')
    ap.add_argument('--per-lang', type=int, default=10)
    args = ap.parse_args()

    labelled = labelled_paths(Path(args.labels))
    rng = random.Random(20260912)
    files = []
    langs_seen = set()
    for lang in TARGET_LANGUAGES:
        d = Path(args.raw) / lang
        if not d.is_dir():
            continue
        pool = [p for p in sorted(d.iterdir())
                if p.is_file() and str(p.resolve()) in labelled]
        rng.shuffle(pool)
        engine, _ = teacher(lang)
        picked = 0
        used: set[str] = set()
        for require_band in (True, False):
            for p in pool:
                if picked >= args.per_lang:
                    break
                if p.name in used:
                    continue
                try:
                    # Strict decode, exactly as build_dataset.py reads it, so
                    # the split hash matches the one used for training.
                    text = p.read_text(encoding='utf-8')
                except (OSError, UnicodeDecodeError):
                    continue
                if split_of(text) != 'test' or len(text) < MIN_CHARS:
                    continue
                if len(text) > MAX_CHARS:
                    if require_band:
                        continue
                    cut = text.rfind('\n', 0, MAX_CHARS)
                    text = text[:cut if cut > MIN_CHARS else MAX_CHARS]
                files.append({'lang': lang, 'shikiLang': shiki_id(lang), 'teacher': engine,
                              'name': p.name[:60], 'code': text})
                used.add(p.name)
                picked += 1
            if picked >= args.per_lang:
                break
        if picked:
            langs_seen.add(lang)

    w = weights()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    header = ('// Generated by train_large/make_demo_corpus_large.py -- do not edit.\n'
               '// Held-out test-split files from train_large/corpus/raw across the\n'
               '// 185-grammar target set, tagged with their labelling teacher.\n\n')
    body = (f'export const WEIGHTS_LARGE = {json.dumps(w, indent=2)};\n\n'
            f'export const CORPUS_LARGE = {json.dumps(files)};\n')
    out.write_text(header + body)
    missing = [l for l in TARGET_LANGUAGES if l not in langs_seen]
    print(f'{len(files)} files across {len(langs_seen)}/{len(TARGET_LANGUAGES)} languages '
          f'-> {out}  ({out.stat().st_size / 1024:.0f} KB)')
    if missing:
        print(f'no test-split files for: {" ".join(missing)}')


if __name__ == '__main__':
    main()
