"""
Bakes the exported model and generated shader into the `lex` package sources.

The weight blob ships inline as base85 rather than as a fetched asset: the
model is ~35 KB, so the extra HTTP round-trip would cost more than the bytes, and
inlining keeps `lex` a single import with no network dependency. Base85 packs 4
bytes into 5 characters (25% overhead) instead of base64's 3-into-4 (33%);
`lex/src/weights-codec.js`'s decoder is a hand-written mirror of this exact
alphabet and padding rule, so this can just call the stdlib encoder.
"""

from __future__ import annotations

import argparse
import base64
import json
from pathlib import Path

import wgsl


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--checkpoint-dir', default='./checkpoints')
    ap.add_argument('--lex-src', default='../lex/src')
    args = ap.parse_args()

    ck = Path(args.checkpoint_dir)
    out = Path(args.lex_src)
    out.mkdir(parents=True, exist_ok=True)

    meta = json.loads((ck / 'weights.meta.json').read_text())
    blob = (ck / 'weights.bin').read_bytes()
    b85 = base64.b85encode(blob).decode()

    slim = {k: meta[k] for k in
            ('format', 'config', 'plane_words', 'f16_count',
             'plane_bytes', 'f16_bytes', 'total_bytes', 'parameters')}
    steps = wgsl.pipeline_order(meta['config']['n_layers'])
    (out / 'weights.js').write_text(
        '// Generated by train/bundle_lex.py -- do not edit.\n'
        f'// {meta["parameters"]:,} parameters, {meta["total_bytes"] / 1024:.2f} KB packed.\n\n'
        f'export const META = {json.dumps(slim, indent=2)};\n\n'
        '// Entry points in execution order. `tile` is the tokens-per-workgroup for\n'
        '// the token-parallel passes; 0 means the pass needs the whole sequence in\n'
        '// one workgroup because it is sequential in t.\n'
        f'export const PIPELINE = {json.dumps(steps)};\n\n'
        f'export const WEIGHTS_B85 =\n  "{b85}";\n')

    shader = wgsl.generate(meta)
    (out / 'shader.wgsl').write_text(shader)
    escaped = shader.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    (out / 'shader.js').write_text(
        '// Generated by train/bundle_lex.py from wgsl.py -- do not edit.\n'
        f'export const SHADER = `{escaped}`;\n')

    print(f'bundled {meta["total_bytes"] / 1024:.2f} KB of weights '
          f'({len(b85) / 1024:.1f} KB base85) + {len(shader) / 1024:.1f} KB shader -> {out}')


if __name__ == '__main__':
    main()
