"""
Bakes the exported model and generated shader into the `lex` package sources.

The weight blob ships inline rather than as a fetched asset: the model is
~28 KB, so the extra HTTP round-trip would cost more than the bytes, and
inlining keeps `lex` a single import with no network dependency.

Weights are two strings -- the packed bit-planes as hex of their bytes, and
the fp16/8-bit scalar tail as base64. Measured after Brotli on the v2 model:
26.82 KiB for this pair, 27.11 base64+base64, 27.15 hex-per-code, 27.77
base85+base85, 26.63 raw binary. 1-bit planes are near-random, so keeping whole
bytes on character boundaries is what compresses best.

The runtime imports `shader.js`, which holds the minified WGSL (comments and
whitespace stripped, declared names shortened -- wgsl.minify). `shader.wgsl`
stays the readable generated source for debugging; both come from the same
wgsl.generate() call.

`lex/src/weights-codec.js` holds the matching decoders.
"""

from __future__ import annotations

import argparse
import base64
import json
from pathlib import Path

import wgsl


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--checkpoint-dir', default='./checkpoints_v2')
    ap.add_argument('--lex-src', default='../lex/src')
    args = ap.parse_args()

    ck = Path(args.checkpoint_dir)
    out = Path(args.lex_src)
    out.mkdir(parents=True, exist_ok=True)

    meta = json.loads((ck / 'weights.meta.json').read_text())
    blob = (ck / 'weights.bin').read_bytes()
    nw = meta['plane_words']
    planes_hex = blob[:nw * 4].hex()
    scalars_b64 = base64.b64encode(blob[nw * 4:]).decode()

    if meta.get('feature_version') != 2 or meta.get('scalar_bits') != 8:
        raise ValueError('bundle_lex.py packages lex-lite exports (feature version 2, 8-bit scalars)')
    # The scalar blob is the fp16 stream followed by the 8-bit codes;
    # f16_count is the size of the decoded float table the shader indexes.
    slim = {k: meta[k] for k in
            ('format', 'config', 'plane_words', 'f16_count', 'f16_stream_count',
             'u8_count', 'scalar_segments', 'plane_bytes', 'f16_bytes',
             'total_bytes', 'parameters')}
    steps = wgsl.pipeline_order(meta['config']['n_layers'])
    (out / 'weights.js').write_text(
        '// Generated by train/bundle_lex.py -- do not edit.\n'
        f'// {meta["parameters"]:,} parameters, {meta["total_bytes"] / 1024:.2f} KB packed.\n\n'
        f'export const META = {json.dumps(slim, separators=(",", ":"))};\n\n'
        '// Entry points in execution order. `tile` is the tokens-per-workgroup for\n'
        '// the token-parallel passes; 0 means the pass needs the whole sequence in\n'
        '// one workgroup because it is sequential in t.\n'
        f'export const PIPELINE = {json.dumps(steps, separators=(",", ":"))};\n\n'
        f'export const WEIGHTS_PLANES_HEX =\n  "{planes_hex}";\n\n'
        f'export const WEIGHTS_SCALARS_B64 =\n  "{scalars_b64}";\n')

    shader = wgsl.generate(meta)
    (out / 'shader.wgsl').write_text(shader)
    small = wgsl.minify(shader, {s['entry'] for s in steps})
    escaped = small.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    (out / 'shader.js').write_text(
        '// Generated by train/bundle_lex.py from wgsl.py (minified; readable source\n'
        '// in shader.wgsl) -- do not edit.\n'
        f'export const SHADER = `{escaped}`;\n')

    print(f'bundled {meta["total_bytes"] / 1024:.2f} KB of weights '
          f'({len(planes_hex) / 1024:.1f} KB planes hex + {len(scalars_b64) / 1024:.1f} KB scalars base64) '
          f'+ {len(small) / 1024:.1f} KB shader (minified from {len(shader) / 1024:.1f}) -> {out}')


if __name__ == '__main__':
    main()
