"""
Emits the demo's evaluation corpora.

Two sets, because they answer different questions:

  held-out files -- from the dataset's *test* split, assigned by hashing the file
    name. Nothing here was trained on, but it comes from the same repositories,
    which share house style and identifier conventions. Fair for tracking
    training; generous to the model when comparing against an engine that never
    saw any of it.

  unseen repos -- from repositories that appear nowhere in repos.py. Both engines
    are out of distribution here, so there is no home-field advantage. This is the
    set to quote in a head-to-head.

Language weights ride along so the demo reproduces the popularity-weighted metric
rather than a corpus-shaped average.
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

from data_pipeline import split_of
from languages import TARGET_LANGUAGES, TOP25_PUSHER_SHARE, shiki_id, weights

MAX_CHARS = 6_000
MIN_CHARS = 300


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument('--raw', default='./corpus/raw')
    ap.add_argument('--out', default='../demo/src/corpus.js')
    ap.add_argument('--per-lang', type=int, default=25)
    ap.add_argument('--name', default='CORPUS')
    ap.add_argument('--all-files', action='store_true',
                    help='use every file, not just the test split (for unseen repos)')
    args = ap.parse_args()

    rng = random.Random(20260909)
    files = []
    for lang in TARGET_LANGUAGES:
        d = Path(args.raw) / lang
        if not d.is_dir():
            continue
        pool = [p for p in sorted(d.iterdir())
                if p.is_file() and (args.all_files or split_of(str(p)) == 'test')]
        rng.shuffle(pool)
        # Two passes. The first takes files that fit the size band as-is; the
        # second truncates larger ones to top up. Without the second pass a
        # language can end up represented by a handful of files -- TypeScript
        # carries 10% of the eval weight and had only three, which makes its
        # score mostly noise.
        picked = 0
        used: set[str] = set()
        for require_band in (True, False):
            for p in pool:
                if picked >= args.per_lang:
                    break
                if p.name in used:
                    continue
                try:
                    text = p.read_text(encoding='utf-8', errors='ignore')
                except OSError:
                    continue
                if len(text) < MIN_CHARS:
                    continue
                if len(text) > MAX_CHARS:
                    if require_band:
                        continue
                    cut = text.rfind('\n', 0, MAX_CHARS)
                    text = text[:cut if cut > MIN_CHARS else MAX_CHARS]
                files.append({'lang': lang, 'shikiLang': shiki_id(lang),
                              'name': p.name[:60], 'code': text})
                used.add(p.name)
                picked += 1
            if picked >= args.per_lang:
                break

    w = weights()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    header = ('// Generated by train/make_demo_corpus.py -- do not edit.\n'
              + ('// Files from repositories absent from repos.py: out of\n'
                 '// distribution for every engine under test.\n\n'
                 if args.all_files else
                 '// Held-out test-split files: the split is a hash of the file\n'
                 '// name, so none of these were seen during training.\n\n'))
    body = f'export const {args.name} = {json.dumps(files)};\n'
    if args.name == 'CORPUS':
        body = (f'export const WEIGHTS = {json.dumps(w, indent=2)};\n\n'
                f'export const TOP25 = {json.dumps(sorted(TOP25_PUSHER_SHARE))};\n\n'
                + body)
    out.write_text(header + body)
    langs = {f['lang'] for f in files}
    print(f'{len(files)} files across {len(langs)}/{len(TARGET_LANGUAGES)} languages '
          f'-> {out}  ({out.stat().st_size / 1024:.0f} KB)')


if __name__ == '__main__':
    main()
